# Generated by Django 3.1.4 on 2020-12-12 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('dob', models.DateField(max_length=25)),
                ('primary_address', models.CharField(max_length=100)),
                ('seconary_adderss', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-binary', 'Non-binary'), ('Transgender', 'Transgender'), ('Intersex', 'Intersex'), ('I prefer not to say', 'I prefer not to say')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Unverified', 'Unverified'), ('Verified', 'Verified')], default='Pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=25)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('percentage', models.CharField(blank=True, max_length=20, null=True)),
                ('year_attained', models.CharField(max_length=25)),
                ('document', models.FileField(blank=True, null=True, upload_to='')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.profile')),
            ],
        ),
    ]
