# Generated by Django 3.1.4 on 2020-12-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20201213_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic',
            name='degree',
            field=models.CharField(default='asdf', max_length=100),
            preserve_default=False,
        ),
    ]
