# Generated by Django 3.1.4 on 2020-12-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_academic_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='designation',
            field=models.CharField(default='Developer', max_length=100),
            preserve_default=False,
        ),
    ]
