# Generated by Django 3.1.4 on 2020-12-18 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_auto_20201214_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_profile', to='profile.profile'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='profile.profile'),
        ),
    ]
